Dry-run release tagging in CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2,6 +2,7 @@ image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:release-tools"
 
 stages:
   - test
+  - dry run
   - deploy
   - automation
   - chatops
@@ -57,6 +58,31 @@ specs:
     paths:
       - coverage/assets
       - coverage/index.html
+
+# dry run ---------------------------------------------------------------------
+
+"release:tag":
+  <<: *except-automation
+  <<: *with-bundle
+  stage: dry run
+  variables:
+    TEST: "true"
+  needs: [ "specs" ]
+  dependencies: []
+  script:
+    - source scripts/setup_ssh.sh
+    - git config --global user.email "you@example.com"
+    - git config --global user.name "Dry Run"
+    - bundle exec rake "release:tag[42.0.0]" > log/release.log
+    - |
+      if grep $'\\[31m' log/release.log ; then
+        echo ""; echo "Failure detected"; exit 1
+      fi
+  artifacts:
+    when: always
+    expire_in: 2 weeks
+    paths:
+      - log/release.log
 
 # deploy ----------------------------------------------------------------------
 
